
import { AppLanguage, TranslationMap } from './types';

export const LANGUAGES = [
  { code: AppLanguage.EN, label: 'English', native: 'English' },
  { code: AppLanguage.HI, label: 'Hindi', native: 'हिन्दी' },
  { code: AppLanguage.TA, label: 'Tamil', native: 'தமிழ்' },
  { code: AppLanguage.TE, label: 'Telugu', native: 'తెలుగు' },
  { code: AppLanguage.ML, label: 'Malayalam', native: 'മലയാളം' },
];

export const TRANSLATIONS: TranslationMap = {
  welcome: {
    en: 'Welcome to Shakti Bridge',
    hi: 'शक्ति ब्रिज में आपका स्वागत है',
    ta: 'சக்தி பிரிட்ஜிற்கு உங்களை வரவேற்கிறோம்',
    te: 'శక్తి బ్రిడ్జ్ కి స్వాగతం',
    ml: 'ശക്തി ബ്രിഡ്ജിലേക്ക് സ്വാഗതം',
  },
  namaste: {
    en: 'Namaste',
    hi: 'नमस्ते',
    ta: 'வணக்கம்',
    te: 'నమస్తే',
    ml: 'നമസ്തേ',
  },
  welcome_home: {
    en: 'Welcome to your Shakti Bridge home. Your global portfolio is ready and live.',
    hi: 'आपके शक्ति ब्रिज होम में आपका स्वागत है। आपका ग्लोबल पोर्टफोलियो तैयार और लाइव है।',
    ta: 'உங்கள் சக்தி பிரிட்ஜ் இல்லத்திற்கு வரவேற்கிறோம். உங்கள் உலகளாவிய போர்ட்ஃபோலியோ தயாராக உள்ளது.',
    te: 'మీ శక్తి బ్రిడ్జ్ హోమ్‌కు స్వాగతం. మీ గ్ローバル పోర్ట్‌ఫోలియో సిద్ధంగా ఉంది.',
    ml: 'നിങ്ങളുടെ ശക്തി ബ്രിഡ്ജ് ഹോമിലേക്ക് സ്വാഗതം. നിങ്ങളുടെ ആഗോള പോർട്ട്‌ഫോളിയോ തയ്യാറാണ്.',
  },
  my_profile: {
    en: 'My Profile',
    hi: 'मेरी प्रोफ़ाइल',
    ta: 'எனது சுயவிவரம்',
    te: 'నా ప్రొఫైల్',
    ml: 'എന്റെ പ്രൊഫൈൽ',
  },
  my_products: {
    en: 'My Products',
    hi: 'मेरे उत्पाद',
    ta: 'எனது தயாரிப்புகள்',
    te: 'నా ఉత్పత్తులు',
    ml: 'എന്റെ ഉൽപ്പന്നങ്ങൾ',
  },
  artisan_community: {
    en: 'Artisan Community',
    hi: 'कलाकार समुदाय',
    ta: 'கைவினைஞர் சமூகம்',
    te: 'కళాకారుల సంఘం',
    ml: 'കരകൗശല കമ്മ്യൂணிറ്റി',
  },
  exit_portal: {
    en: 'Exit Portal',
    hi: 'पोर्टल से बाहर निकलें',
    ta: 'வெளியேறு',
    te: 'నిష్క్రమించు',
    ml: 'പുറത്തുകടക്കുക',
  },
  operations_portal: {
    en: 'Operations Portal',
    hi: 'संचालन पोर्टल',
    ta: 'செயல்பாட்டு மையம்',
    te: 'ఆపరేషన్స్ పోర్టల్',
    ml: 'ഓപ്പറേഷൻസ് പോർട്ടൽ',
  },
  artisan_series: {
    en: 'SHAKTI BRIDGE ARTISAN SERIES NO.',
    hi: 'शक्ति ब्रिज कलाकार श्रृंखला संख्या',
    ta: 'சக்தி பிரிட்ஜ் கைவினைஞர் வரிசை எண்.',
    te: 'శక్తి బ్రిడ్జ్ కళాకారుల సిరీస్ నం.',
    ml: 'ശക്തി ബ്രിഡ്ജ് കരകൗശല പരമ്പര നം.',
  },
  master_of: {
    en: 'Master of',
    hi: 'के मास्टर',
    ta: 'நிபுணர்',
    te: 'నిపుణుడు',
    ml: 'വിദഗ്ദ്ധൻ',
  },
  philosophy: {
    en: 'Philosophy & Origin',
    hi: 'दर्शन और उत्पत्ति',
    ta: 'தத்துவம் மற்றும் தோற்றம்',
    te: 'తత్వశాస్త్రం మరియు మూలం',
    ml: 'തത്വശാസ്ത്രവും ഉത്ഭവവും',
  },
  origin: {
    en: 'Origin',
    hi: 'उत्पत्ति',
    ta: 'தோற்றம்',
    te: 'మూలం',
    ml: 'ഉത്ഭവം',
  },
  heritage_grade: {
    en: 'Heritage Grade',
    hi: 'विरासत ग्रेड',
    ta: 'பாரம்பரிய தரம்',
    te: 'వారసత్వ గ్రేడ్',
    ml: 'പൈതൃക ഗ്രേഡ്',
  },
  material_focus: {
    en: 'Material Focus',
    hi: 'सामग्री फोकस',
    ta: 'பொருள் கவனம்',
    te: 'మెటీరియల్ ఫోకస్',
    ml: 'మెറ്റീരിയൽ ഫോക്കസ്',
  },
  artisan_voice: {
    en: 'The Artisan’s Voice',
    hi: 'कलाकार की आवाज़',
    ta: 'கைவினைஞரின் குரல்',
    te: 'కళాకారుడి స్వరం',
    ml: 'കരകൗശല വിദഗ്ധന്റെ ശബ്ദം',
  },
  curated_collection: {
    en: 'Curated Collection',
    hi: 'क्यूरेटेड संग्रह',
    ta: 'தொகுக்கப்பட்ட சேகரிப்பு',
    te: 'క్యూరేటెడ్ సేకరణ',
    ml: 'തിരഞ്ഞെടുത്ത ശേഖരം',
  },
  view_inventory: {
    en: 'View Inventory',
    hi: 'सूची देखें',
    ta: 'இருப்பு விவரங்களைப் பார்க்கவும்',
    te: 'ఇన్వెంటరీని వీక్షించండి',
    ml: 'ഇൻവെന്ററി കാണുക',
  },
  inventory_control: {
    en: 'Inventory Control',
    hi: 'इन्वेंटरी नियंत्रण',
    ta: 'சரக்கு மேலாண்மை',
    te: 'ఇన్వెంటరీ నియంత్రణ',
    ml: 'ఇൻవెന്ററി నియంత్రణం',
  },
  archive_new_piece: {
    en: 'Archive New Piece',
    hi: 'नया पीस आर्काइव करें',
    ta: 'புதிய பொருளைச் சேர்க்கவும்',
    te: 'కొత్త భాగాన్ని ఆర్కైవ్ చేయండి',
    ml: 'പുതിയ ഇനം ആർക്കൈവ് ചെയ്യുക',
  },
  no_items_cataloged: {
    en: 'No items currently cataloged',
    hi: 'वर्तमान में कोई आइटम सूचीबद्ध नहीं है',
    ta: 'தற்போது எந்த பொருட்களும் பட்டியலிடப்படவில்லை',
    te: 'ప్రస్తుతం ఐటెమ్‌లు ఏవీ కేటలాగ్ చేయబడలేదు',
    ml: 'നിലവിൽ ഇനങ്ങളൊന്നും കാറ്റലോഗ് ചെയ്തിട്ടില്ല',
  },
  guild_network: {
    en: 'GUILD NETWORK',
    hi: 'गिल्ड नेटवर्क',
    ta: 'கைவினைஞர் கூட்டமைப்பு',
    te: 'గిల్డ్ నెట్‌వర్క్',
    ml: 'ഗിൽഡ് നെറ്റ്‌വർക്ക്',
  },
  guild_collective: {
    en: 'The Shakti Guild Collective',
    hi: 'शक्ति गिल्ड कलेक्टिव',
    ta: 'சக்தி கைவினைஞர் குழுமம்',
    te: 'శక్తి గిల్డ్ కలెక్టివ్',
    ml: 'ശக்தி ഗിൽഡ് കളക്ടീവ്',
  },
  master_artisan_msg: {
    en: 'verified master artisans connected by a single vision: Bridging legacy with modernity.',
    hi: 'सत्यापित मास्टर कलाकार एक ही विजन से जुड़े हैं: आधुनिकता के साथ विरासत को जोड़ना।',
    ta: 'ஒற்றை பார்வையால் இணைக்கப்பட்ட சரிபார்க்கப்பட்ட கைவினைஞர்கள்: பாரம்பரியத்தை நவீனத்துடன் இணைத்தல்.',
    te: 'ధృవీకరించబడిన మాస్టర్ కళాకారులు ఒకే దృష్టితో కనెక్ట్ అయ్యారు: వారసత్వాన్ని ఆధునికతతో అనుసంధానించడం.',
    ml: 'ഒറ്റ കാഴ്ചപ്പാടിലൂടെ ബന്ധിപ്പിച്ചിട്ടുള്ള പരിശോധിച്ചുറപ്പിച്ച മാസ്റ്റർ കരകൗശല വിദഗ്ധർ: പൈതൃകത്തെ ആധുനികതയുമായി ബന്ധിപ്പിക്കുന്നു.',
  },
  export_quality: {
    en: 'Export Quality',
    hi: 'निर्यात गुणवत्ता',
    ta: 'ஏற்றுமதி தரம்',
    te: 'ఎగుమతి నాణ్యత',
    ml: 'കയറ്റുമതി ഗുണനിലവാരം',
  },
  available_globally: {
    en: 'Available Globally',
    hi: 'विश्व स्तर पर उपलब्ध',
    ta: 'உலகளவில் கிடைக்கிறது',
    te: 'ప్రపంచవ్యాప్తంగా అందుబాటులో ఉంది',
    ml: 'ആഗോളതലത്തിൽ ലഭ്യമാണ്',
  },
  current_exhibition: {
    en: 'Current Exhibition',
    hi: 'वर्तमान प्रदर्शनी',
    ta: 'தற்போதைய கண்காட்சி',
    te: 'ప్రస్తుత ప్రదర్శన',
    ml: 'നിലവിലെ പ്രദർശനം',
  },
  featured_treasures: {
    en: 'Featured Treasures',
    hi: 'विशेष खजाने',
    ta: 'சிறப்பு படைப்புகள்',
    te: 'ఫీచర్ చేయబడిన సంపదలు',
    ml: 'തിരഞ്ഞെടുത്ത നിധികൾ',
  },
  shop_collection: {
    en: 'Shop Collection',
    hi: 'संग्रह खरीदें',
    ta: 'சேகரிப்பை வாங்கவும்',
    te: 'సేకరణను షాపింగ్ చేయండి',
    ml: 'ശേഖരം ഷോപ്പ് ചെയ്യുക',
  },
  handmade: {
    en: 'Handmade',
    hi: 'हाथ से बना',
    ta: 'கைவினைப்பொருள்',
    te: 'చేతితో తయారు చేయబడింది',
    ml: 'കൈകൊണ്ട് നിർമ്മിച്ചത്',
  },
  tagline: {
    en: 'Empowering Rural Women through Traditional Crafts',
    hi: 'पारंपरिक शिल्प के माध्यम से ग्रामीण महिलाओं को सशक्त बनाना',
    ta: 'பாரம்பரிய கைவினைப்பொருட்கள் மூலம் கிராமப்புற பெண்களை மேம்படுத்துதல்',
    te: 'సాంప్రదాయ కళల ద్వారా గ్రామీణ మహిళల సాధికారత',
    ml: 'പരമ്പരാഗത കരകൗശലവിദ്യയിലൂടെ ഗ്രാമീണ സ്ത്രീകളെ ശാക്തീകരിക്കുന്നു',
  },
  i_am_seller: {
    en: 'I Am a Seller',
    hi: 'मैं एक विक्रेता हूँ',
    ta: 'நான் ஒரு விற்பனையாளர்',
    te: 'నేను విక్రేతను',
    ml: 'ഞാൻ ഒരു വിൽപനക്കാരനാണ്',
  },
  i_am_buyer: {
    en: 'I Am a Buyer',
    hi: 'मैं एक खरीदार हूँ',
    ta: 'நான் ஒரு வாங்குபவர்',
    te: 'నేను కొనుగోలుదారుని',
    ml: 'ഞാൻ ഒരു വാങ്ങുന്നയാളാണ്',
  },
  start_now: {
    en: 'Start Now',
    hi: 'अभी शुरू करें',
    ta: 'இப்போது தொடங்கவும்',
    te: 'ఇప్పుడే ప్రారంభించండి',
    ml: 'ഇപ്പോൾ ആരംഭിക്കുക',
  },
  browse_gallery: {
    en: 'Browse Gallery',
    hi: 'गैलरी देखें',
    ta: 'கேலரியைப் பார்க்கவும்',
    te: 'గ్యాలరీని బ్రౌజ్ చేయండి',
    ml: 'ഗാലറി ബ്രൗസ് ചെയ്യുക',
  },
  seller_desc: {
    en: 'Sell your handmade crafts. We handle the rest.',
    hi: 'अपने हस्तनिर्मित शिल्प बेचें। बाकी हम संभाल लेंगे।',
    ta: 'உங்கள் கைவினைப்பொருட்களை விற்கவும். மற்றவற்றை நாங்கள் கவனித்துக்கொள்வோம்.',
    te: 'మీ చేతిపనులను విక్రయించండి. మిగిలినవి మేము చూసుకుంటాము.',
    ml: 'നിങ്ങളുടെ കരകൗശല ഉൽപ്പന്നങ്ങൾ വിൽക്കുക. ബാക്കി ഞങ്ങൾ നോക്കും.',
  },
  buyer_desc: {
    en: 'Discover authentic rural Indian artistry.',
    hi: 'प्रामाणिक ग्रामीण भारतीय कला की खोज करें।',
    ta: 'உண்மையான கிராமப்புற இந்திய கலைத்திறனைக் கண்டறியவும்.',
    te: 'నిజమైన గ్రామీణ భారతీయ కళాత్మకతను కనుగొనండి.',
    ml: 'യഥാർത്ഥ ഗ്രാമീణ ഇന്ത്യൻ കലാവൈഭവം കണ്ടെത്തുക.',
  },
  platform_fee: {
    en: 'Platform Revenue',
    hi: 'प्लेटफ़ॉर्म राजस्व',
    ta: 'தள வருவாய்',
    te: 'ప్లాట్‌ఫారమ్ ఆదాయం',
    ml: 'പ്ലാറ്റ്ഫോം വരുമാനം',
  },
  base_p: {
    en: 'Base Price',
    hi: 'आधार मूल्य',
    ta: 'அசல் விலை',
    te: 'బేస్ ధర',
    ml: 'അടിസ്ഥാന വില',
  },
  markup_p: {
    en: 'Markup',
    hi: 'मार्कअप',
    ta: 'கூடுதல் விலை',
    te: 'మార్కప్',
    ml: 'മാർക്കപ്പ്',
  },
  buyer_login_title: {
    en: 'Buyer Registration',
    hi: 'खरीदार पंजीकरण',
    ta: 'வாங்குபவர் பதிவு',
    te: 'కొనుగోలుదారు రిజిస్ట్రేషన్',
    ml: 'വാങ്ങുന്നയാളുടെ രജിസ്ട്രേഷൻ',
  },
  buyer_login_desc: {
    en: 'Join the community to support rural artisans and track your unique craft collection.',
    hi: 'ग्रामीण कलाकारों का समर्थन करने और अपने अद्वितीय शिल्प संग्रह को ट्रैक करने के लिए समुदाय में शामिल हों।',
    ta: 'கைவினைஞர்களுக்கு ஆதரவளிக்கவும் உங்கள் கைவினைப் பொருட்களைக் கண்காணிக்கவும் சமூகத்தில் இணையுங்கள்.',
    te: 'గ్రామీణ కళాకారులకు మద్దతు ఇవ్వడానికి మరియు మీ ప్రత్యేకమైన క్రాఫ్ట్ సేకరణను ట్రాక్ చేయడానికి సంఘంలో చేరండి.',
    ml: 'കരകൗശല വിദഗ്ധരെ പിന്തുണയ്ക്കുന്നതിനും നിങ്ങളുടെ തനതായ ശേഖരം ട്രാക്ക് ചെയ്യുന്നതിനും കമ്മ്യൂണിറ്റിയിൽ ചേരുക.',
  },
  buyer_name: {
    en: 'Buyer Name',
    hi: 'खरीदार का नाम',
    ta: 'வாங்குபவர் பெயர்',
    te: 'కొనుగోలుదారు పేరు',
    ml: 'വാങ്ങുന്നയാളുടെ പേര്',
  },
  shipping_address: {
    en: 'Shipping Address',
    hi: 'शिपिंग का पता',
    ta: 'விநியோக முகவரி',
    te: 'షిప్పింగ్ చిరునామా',
    ml: 'షిప్పిംഗ് వിലാസം',
  },
  continue_to_market: {
    en: 'Continue to Marketplace',
    hi: 'बाज़ार की ओर बढ़ें',
    ta: 'சந்தைக்குச் செல்லவும்',
    te: 'మార్కెట్‌ప్లేస్‌కు కొనసాగండి',
    ml: 'മാർക്കറ്റ് പ്ലേസിലേക്ക് തുടരുക',
  },
  artisan_masterpieces: {
    en: 'Artisan Masterpieces',
    hi: 'कलाकार की उत्कृष्ट कृतियाँ',
    ta: 'கைவினைச் சிறப்புகள்',
    te: 'కళాఖండాలు',
    ml: 'കരകൗശല വിസ്മയങ്ങൾ',
  },
  managed_by: {
    en: 'Curated, verified, and managed by Shakti Bridge Team.',
    hi: 'शक्ति ब्रिज टीम द्वारा क्यूरेटेड, सत्यापित और प्रबंधित।',
    ta: 'சக்தி பிரிட்ஜ் குழுவால் நிர்வகிக்கப்படும் படைப்புகள்.',
    te: 'శక్తి బ్రిడ్జ్ టీమ్ ద్వారా నిర్వహించబడుతుంది.',
    ml: 'ശക്തി ബ്രിഡ്ജ് ടീം നിയന്ത്രിക്കുന്ന സൃഷ്ടികൾ.',
  },
  contact_team: {
    en: 'Contact Team',
    hi: 'टीम से संपर्क करें',
    ta: 'குழுவைத் தொடர்பு கொள்க',
    te: 'టీమ్‌ను సంప్రదించండి',
    ml: 'ടീമിനെ ബന്ധപ്പെടുക',
  },
  all_categories: {
    en: 'All',
    hi: 'सभी',
    ta: 'அனைத்தும்',
    te: 'అన్నీ',
    ml: 'എല്ലാം',
  },
  checkout_title: {
    en: 'Secure Checkout',
    hi: 'सुरक्षित चेकआउट',
    ta: 'பாதுகாப்பான பரிவர்த்தனை',
    te: 'సురక్షిత చెక్అవుట్',
    ml: 'സുരക്ഷിത ചെക്ക്ഔട്ട്',
  },
  quantity: {
    en: 'Quantity',
    hi: 'मात्रा',
    ta: 'அளவு',
    te: 'పరిమాణం',
    ml: 'അളവ്',
  },
  payment_method: {
    en: 'Payment Method',
    hi: 'भुगतान का तरीका',
    ta: 'கட்டண முறை',
    te: 'చెల్లింపు పద్ధతి',
    ml: 'പേയ്‌മെന്റ് രീതി',
  },
  confirm_order: {
    en: 'Confirm & Place Order',
    hi: 'पुष्टि करें और ऑर्डर दें',
    ta: 'ஆர்டரை உறுதிசெய்க',
    te: 'ఆర్డర్‌ని ధృవీకరించండి',
    ml: 'ഓർഡർ സ്ഥിരീകരിക്കുക',
  },
  order_success: {
    en: 'Order Confirmed!',
    hi: 'ऑर्डर की पुष्टि हो गई!',
    ta: 'ஆர்டர் உறுதி செய்யப்பட்டது!',
    te: 'ఆర్డర్ ధృవీకరించబడింది!',
    ml: 'ഓർഡർ സ്ഥിരീകരിച്ചു!',
  },
  order_success_msg: {
    en: 'Your unique treasure is being prepared. Thank you for supporting rural legacy.',
    hi: 'आपका अद्वितीय खजाना तैयार किया जा रहा है। ग्रामीण विरासत का समर्थन करने के लिए धन्यवाद।',
    ta: 'உங்கள் படைப்பு தயாராகி வருகிறது. கிராமப்புற கலைக்கு ஆதரவளித்தமைக்கு நன்றி.',
    te: 'మీ ప్రత్యేకమైన సంపద సిద్ధమవుతోంది. గ్రామీణ వారసత్వానికి మద్దతు ఇచ్చినందుకు ధన్యవాదాలు.',
    ml: 'നിങ്ങളുടെ അദ്വിതീയ നിധി തയ്യാറാക്കുന്നു. ഗ്രാമീണ പൈതൃകത്തെ പിന്തുണച്ചതിന് നന്ദി.',
  },
  phone_number: {
    en: 'Phone Number',
    hi: 'फ़ोन नंबर',
    ta: 'தொலைபேசி எண்',
    te: 'ఫోన్ నంబర్',
    ml: 'ഫോൺ നമ്പർ',
  }
};

export const INITIAL_PRODUCTS: any[] = [
  {
    id: 'p1',
    sellerId: 's1',
    nameEn: 'Hand-woven Bamboo Basket',
    nameNative: 'हाथ से बुनी बांस की टोकरी',
    descriptionEn: 'Sturdy and beautiful basket made from local forest bamboo.',
    descriptionNative: 'स्थानीय वन बांस से बनी मजबूत और सुंदर टोकरी।',
    basePrice: 450,
    markupPercent: 6,
    price: 477,
    imageUrl: 'https://images.unsplash.com/photo-1591084728795-1149f32d9866?auto=format&fit=crop&q=80&w=800',
    category: 'Home Decor',
    status: 'available',
    rating: 4.8
  },
  {
    id: 'p2',
    sellerId: 's2',
    nameEn: 'Terracotta Painted Pot',
    nameNative: 'टेराकोटा चित्रित बर्तन',
    descriptionEn: 'Traditional motifs painted on high-quality terracotta.',
    descriptionNative: 'उच्च गुणवत्ता वाले टेराकोटा पर चित्रित पारंपरिक रूपांकन।',
    basePrice: 800,
    markupPercent: 7,
    price: 856,
    imageUrl: 'https://images.unsplash.com/photo-1610701596007-11502861dcfa?auto=format&fit=crop&q=80&w=800',
    category: 'Pottery',
    status: 'available',
    rating: 4.5
  },
  {
    id: 'p3',
    sellerId: 's3',
    nameEn: 'Pure Silk Saree',
    nameNative: 'கான்ஜிவரம் பட்டு புடவை',
    descriptionEn: 'Hand-loomed luxury silk with traditional gold-threaded borders.',
    descriptionNative: 'பாரம்பரியமான முறையில் நெய்யப்பட்ட ஆடம்பரமான பட்டுப் புடவை.',
    basePrice: 2000,
    markupPercent: 6,
    price: 2120,
    imageUrl: 'https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?auto=format&fit=crop&q=80&w=800',
    category: 'Textiles',
    status: 'available',
    rating: 4.9
  }
];
